### ISSUE TITLE
User \"system:anonymous\" cannot \"proxy\" \"services\" with name \"fabric8-forge\" in project \"default\"

### ISSUE THREAD

**Issue by ckemmler** [fabric8io/fabric8-console#78] opened 2016-01-14 10:14 UTC
I'm hitting this error upon browsing to: `http://fabric8.apps.intrinsic.world/workspaces/default/forge/command/project-new` (new Java project)

In Chrome's console I can see:

```
Failed to load resource: the server responded with a status of 503 (Service Unavailable)
libs.js:39375 [Forge] Failed to load https://paas.intrinsic.world:8443/api/v1/proxy/namespaces/default/services/…ject-new?secret=gogs-https-admin&secretNamespace=user-secrets-source-admin Error: 'dial tcp 10.1.0.7:8080: i/o timeout'
Trying to reach: 'http://10.1.0.7:8080/api/forge/commandInput/project-new?secret=gogs-https-admin&secretNamespace=user-secrets-source-admin' 503
```

The console reports not being able to call the following endpoint:

`https://paas.intrinsic.world:8443/api/v1/proxy/namespaces/default/services/fabric8-forge/api/forge/command/validate/project-new?secret=candide&secretNamespace=user-secrets-source-admin`

When I open it in a separate browser window, I get:
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "User \"system:anonymous\" cannot \"proxy\" \"services\" with name \"fabric8-forge\" in project \"default\"",
  "reason": "Forbidden",
  "details": {
    "name": "fabric8-forge",
    "kind": "services"
  },
  "code": 403
}
```

I don't even know how to start debugging this problem. I'd love to have some pointers. What it looks like is that the user I'm authenticated with (admin) has not propagated the authentication context to the point where it calls the above URL. I struggled to get fabric8 to work on a master-node setup and had to go through great length to make sure that authentication worked while the fabric8 app is running on the node and authentication actually takes place on the master. I suspect that, perhaps, the session token is not available everywhere it is needed. But that's just anyone's guess.

**Comment by quappi** [comment] 2016-07-25 09:53
Hi Candide,

have you found a solution for this problem, yet? We're working on fabric8 for a university project and stuck on the same issue right now.

Thanks a lot and have a nice day!
Frederik

**Comment by ckemmler** [comment] 2016-07-25 13:49
Hi,

Sorry no I haven't and , tbh, I eventually gave up with fabric8 altogether and decided to deep dive into openshift first. I found out that I had already more than I could ask – and singlehandedly handle – with OS alone.

C

**Comment by jstrachan** [comment] 2016-09-11 07:00
I think this is now fixed - it was caused by a change in the underlying proxy handling in kubernetes/openshift. We now have to append the port number/name when using the proxy URL - so it needs to be of the form (notice the added `:80`):
```
https://paas.intrinsic.world:8443/api/v1/proxy/namespaces/default/services/fabric8-forge:80/api/forge/command/validate/project-new?secret=candide&secretNamespace=user-secrets-source-admin
```

**Closed by jstrachan** 2016-09-11 07:00 UTC
